parameters:
#    brocoutes_brocante.example.class: Brocoutes\BrocanteBundle\Example

services:
#    brocoutes_brocante.example:
#        class: %brocoutes_brocante.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
